version: '2'

services:
  stats:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE="${RABBITMQ_ERL_COOKIE}"
      - RABBITMQ_USERNAME="${RABBITMQ_USERNAME}"
      - RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD}"
    ports:
      - 15672:${RABBITMQ_MANAGEMENT_PORT}
      - 5672:${RABBITMQ_PORT}
  queue-disc1:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE="${RABBITMQ_ERL_COOKIE}"
  queue-ram1:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE="${RABBITMQ_ERL_COOKIE}"
